import Foundation

public struct Theme: Identifiable, Codable, Equatable, Sendable {
    public let id: String
    public let name: String
    public let subtitle: String
    public let background: String
    public let foreground: String
    public let accent: String
    public let selection: String
    public let cursor: String
    public let palette: [String]
    public let mode: String?
    public var fontFamily: String? = nil
    public var useDefaultFont: Bool? = nil
    public var keepsFont: Bool { fontFamily == nil && useDefaultFont != true }
    public var ghosttyFontConfig: String {
        guard !keepsFont else { return "" }
        let names = ["font-family", "font-family-bold", "font-family-italic", "font-family-bold-italic"]
        return (names.map { "\($0) =" } + (fontFamily.map { ["font-family = \($0)"] } ?? [])).joined(separator: "\n") + "\n"
    }

    public init(id: String, name: String, subtitle: String, background: String, foreground: String, accent: String, selection: String, cursor: String, palette: [String], mode: String? = nil) {
        self.id = id; self.name = name; self.subtitle = subtitle
        self.background = background; self.foreground = foreground; self.accent = accent
        self.selection = selection; self.cursor = cursor; self.palette = palette; self.mode = mode
    }

    private enum CodingKeys: String, CodingKey { case id, name, subtitle, background, foreground, accent, selection, cursor, palette, mode, fontFamily, useDefaultFont }

    public init(from decoder: any Decoder) throws {
        let values = try decoder.container(keyedBy: CodingKeys.self)
        let palette = try values.decode([String].self, forKey: .palette)
        let background = try values.decode(String.self, forKey: .background)
        let foreground = try values.decode(String.self, forKey: .foreground)
        let accent = try values.decode(String.self, forKey: .accent)
        let selection = try values.decode(String.self, forKey: .selection)
        let cursor = try values.decode(String.self, forKey: .cursor)
        let font = try values.decodeIfPresent(String.self, forKey: .fontFamily)
        if let font, font.range(of: "^[A-Za-z0-9][A-Za-z0-9 ._-]{0,99}$", options: .regularExpression) == nil {
            throw ThemeError.message("The saved theme has an invalid font family.")
        }
        let mode = try values.decodeIfPresent(String.self, forKey: .mode)
        guard palette.count == 16,
              (palette + [background, foreground, accent, selection, cursor]).allSatisfy({ $0.range(of: "^#[0-9A-Fa-f]{6}$", options: .regularExpression) != nil }),
              mode == nil || mode == "light" || mode == "dark" else {
            throw ThemeError.message("The saved theme has an invalid color palette. Its files were left unchanged.")
        }
        self.init(id: try values.decode(String.self, forKey: .id), name: try values.decode(String.self, forKey: .name), subtitle: try values.decode(String.self, forKey: .subtitle), background: background, foreground: foreground, accent: accent, selection: selection, cursor: cursor, palette: palette, mode: mode)
        fontFamily = font
        useDefaultFont = try values.decodeIfPresent(Bool.self, forKey: .useDefaultFont)
        guard font == nil || useDefaultFont != true else { throw ThemeError.message("The saved theme has conflicting font choices.") }
    }

    public var isLight: Bool {
        if let mode { return mode == "light" }
        func luminance(_ hex: String) -> Double {
            let rgb = ScriptLiteral.rgb(hex).map { Double($0) / 65_535 }
            return rgb[0] * 0.2126 + rgb[1] * 0.7152 + rgb[2] * 0.0722
        }
        return luminance(background) > luminance(foreground)
    }

    public var ghosttyConfig: String {
        (["# Generated by Mac Themes", "background = \(background)", "foreground = \(foreground)", "cursor-color = \(cursor)", "selection-background = \(selection)", "selection-foreground = \(cursor)"] + palette.enumerated().map { "palette = \($0.offset)=\($0.element)" }).joined(separator: "\n") + "\n" + ghosttyFontConfig
    }
}

public enum ThemeError: LocalizedError {
    case message(String)
    public var errorDescription: String? {
        switch self { case .message(let text): return text }
    }
}

/// Only the marked include is owned by this application. All surrounding bytes survive.
public enum ManagedConfig {
    public static let start = "# >>> Mac Themes >>>"
    public static let end = "# <<< Mac Themes <<<"
    public static func write(_ content: String, to url: URL) throws {
        let target = url.resolvingSymlinksInPath()
        let files = FileManager.default
        let permissions = (try? files.attributesOfItem(atPath: target.path)[.posixPermissions]) as? NSNumber
        try files.createDirectory(at: target.deletingLastPathComponent(), withIntermediateDirectories: true)
        try content.write(to: target, atomically: true, encoding: .utf8)
        if let permissions { try files.setAttributes([.posixPermissions: permissions], ofItemAtPath: target.path) }
    }
    public static func removing(from source: String) throws -> String {
        let starts = source.components(separatedBy: start).count - 1
        let ends = source.components(separatedBy: end).count - 1
        guard starts == ends, starts <= 1 else {
            throw ThemeError.message("The Mac Themes block was edited. Review the Ghostty config before applying.")
        }
        guard starts == 1, let a = source.range(of: start), let b = source.range(of: end), a.lowerBound < b.lowerBound else {
            if starts == 0 { return source }
            throw ThemeError.message("The Mac Themes block has invalid markers.")
        }
        var upper = b.upperBound
        if source[upper...].hasPrefix("\n") { upper = source.index(after: upper) }
        // The block starts with a dedicated newline so removal restores the original trailing newline.
        var lower = a.lowerBound
        if lower > source.startIndex, source[source.index(before: lower)] == "\n" { lower = source.index(before: lower) }
        return String(source[..<lower]) + String(source[upper...])
    }

    public static func applying(to source: String, includePath: String) throws -> String {
        guard !includePath.contains("\n"), !includePath.contains("\r") else {
            throw ThemeError.message("The config path contains an unsupported newline.")
        }
        return try removing(from: source) + "\n\(start)\nconfig-file = \(includePath)\n\(end)\n"
    }
}

public enum ScriptLiteral {
    public static func string(_ value: String) -> String {
        "\"" + value.replacingOccurrences(of: "\\", with: "\\\\").replacingOccurrences(of: "\"", with: "\\\"").replacingOccurrences(of: "\r", with: "\\r").replacingOccurrences(of: "\n", with: "\\n") + "\""
    }
    public static func rgb(_ hex: String) -> [Int] {
        guard hex.range(of: "^#[0-9A-Fa-f]{6}$", options: .regularExpression) != nil,
              let n = UInt32(hex.dropFirst(), radix: 16) else { return [0, 0, 0] }
        return [Int((n >> 16) & 255) * 257, Int((n >> 8) & 255) * 257, Int(n & 255) * 257]
    }
    public static func list(_ values: [Int]) -> String { "{" + values.map(String.init).joined(separator: ", ") + "}" }
}
